### ISSUE TITLE
[csv-renderer] Kibana do not load

### ISSUE THREAD

**Issue by daverick** [cqliu1/canvas-csv-renderer#1]
Looks like one css file ( `built_assets/css/plugins/canvas-csv-renderer/style/index.light.css`)  is not present and prevent Kibana to load properly.

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/19835922/74366330-1ccdb100-4dd0-11ea-9a5c-106af1c06d76.png">

**Comment by cqliu1** [comment]
I fixed the path to the custom CSS for this plugin. This bug is fixed as of 3d9d038f90df063702be8d3624a9960d30cdd3f6.
